PinkFlamingoStudios/Controllers/PFSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PinkFlamingoStudios.Models;

namespace PinkFlamingoStudios.Controllers
{
    public class PFSController : Controller
    {
        // GET: PFS
        PinkFlamingosEntities pf = new PinkFlamingosEntities();
        BusinessLogic bl = new BusinessLogic();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AboutUs()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Contact(sendEmail email)
        {
            if (ModelState.IsValid)
            {
                bl.sendMail(email.Email, email.msg);
            }
           
            return View();
        }

        public ActionResult PreOrder()
        {
            BusinessLogic.name = false;
            BusinessLogic.creditCard = false;
            BusinessLogic.address = false;
            return View("PreOrder");
        }

        [HttpPost]
        public ActionResult PreOrder(PreOrder order, creditCardInfo creditCard)
        {
            if(order.firstName == null && creditCard.creditCardNumber != null)  
            {
                if(creditCard != null)
                {
                    creditCard.idUser = 1;
                    pf.creditCardInfoes.Add(creditCard);
                    pf.SaveChanges();
                    BusinessLogic.name = true;

                    return View("PreOrder");
                }
                return View();
            }
            else 
            {

                    pf.PreOrders.Add(order);
                    pf.SaveChanges();
                    BusinessLogic.name = true;
                    BusinessLogic.creditCard = true;
                
                return View("CreditCard2");
            }
          
           
        }

        [HttpPost]
        public ActionResult CreditCard(creditCardInfo creditCard)
        {

            if (ModelState.IsValid)
            {
                pf.creditCardInfoes.Add(creditCard);
                pf.SaveChanges();
                BusinessLogic.name = true;
            }
            return View();
        }
    }
}

PinkFlamingoStudios/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Pink Flamingo Games</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pink Flamingo Games", "Index", "PFS", new { area = "" }, new { @class = "navbar-brand"})
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "PFS")</li>
                    <li>@Html.ActionLink("About", "AboutUs", "PFS")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "PFS")</li>
                    <li>@Html.ActionLink("Pre-Order", "PreOrder", "PFS")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Pink Flamingo Games</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>